##################################
#         Global settings        #
##################################
listen_addresses = ['127.0.0.1:53533', '[::1]:53533']
server_names = ['cloudflare', 'cloudflare-ipv6', 'quad9-dnscrypt-ip4-filter-pri', 'quad9-doh-ip4-filter-pri', 'quad9-doh-ip6-filter-pri']
fallback_resolvers = ['8.8.8.8:53', '8.8.4.4:53']
netprobe_address = '9.9.9.9:53'

max_clients = 250
timeout = 5000

ignore_system_dns = true

ipv4_servers = true
ipv6_servers = true
block_ipv6 = false

dnscrypt_servers = true
doh_servers = true

log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1

###########################
#        DNS cache        #
###########################
cache = true
cache_size = 10000
cache_min_ttl = 0
#cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

###############################
#        Query logging        #
###############################
[query_log]
file = '/var/log/dnscrypt-proxy/query.log'
[nx_log]
file = '/var/log/dnscrypt-proxy/nx.log'

#############################################
#        Public resolvers and Relays        #
#############################################
[sources]
[sources.'public-resolvers']
urls = ['https://download.dnscrypt.net/resolvers-list/v3/public-resolvers.md']
cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
prefix = ''
[sources.'relays']
urls = ['https://download.dnscrypt.net/resolvers-list/v3/relays.md']
cache_file = '/var/cache/dnscrypt-proxy/relays.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 72
prefix = ''
